{% set name = "pyftpdlib" %}
{% set version = "1.5.4" %}
{% set sha256 = "105955ac7ec1b83e8c5c8dfff206cae3c31a229ef8682b9b1f70ba21f9cb151e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: release-{{ version }}.tar.gz
  url: https://github.com/giampaolo/pyftpdlib/archive/release-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyftpdlib = clcache:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyopenssl
  run:
    - python
    - pyopenssl

test:
  imports:
    - pyftpdlib
    - pyftpdlib.authorizers
    - pyftpdlib.handlers
    - pyftpdlib.filesystems
    - pyftpdlib.servers
    - pyftpdlib.ioloop
  commands:
    - python -m pyftpdlib --help

about:
  home: https://github.com/giampaolo/pyftpdlib
  license: MIT
  license_file: LICENSE
  summary: 'pyftpdlib is a high-level library to easily write asynchronous portable FTP servers with Python.'
  description: |
    Python FTP server library provides a high-level portable interface to easily
    write very efficient, scalable and asynchronous FTP servers with Python. It
    is the most complete RFC-959 FTP server implementation available for Python
    programming language and it's used in projects like Google Chromium and Bazaar
    and included in Debian, Fedora and FreeBSD package repositories.
  doc_url: http://pythonhosted.org/pyftpdlib/
  dev_url: https://github.com/giampaolo/pyftpdlib

extra:
  recipe-maintainers:
    - edisongustavo
    - nicoddemus
    - tadeu
