travis:
  secure:
    BINSTAR_TOKEN: qQ9WAyrqei8F8p9Q78qF0YWfBi0ckOi0xkZJ7/cAWzL6ZoWzsHm6M2qh/sfjKjS0KeQwCeuLH1qskMs9q7INU+1rvql+Bza81bFmkdLm/xv3W6WL9A2IV+ZJPPjUxv6j8j1cfbqt0ByMXJ9XFpCmNnSusk6nE+P9SvV7qQQ+chUzB/nTShjPtx5iU0I4k8PgIxB/opLoUFB6plbiIQeOcTj68vBvWMeNRD1WgCGU19WZGJZoEF6meYuI2d6DMmPxugK8O7fHjWr6ZK6kvgVSX5fOERT4FjGweHyNhDfiWOcbtfvyI9qUEksWBjVYy66jhEZphnK7vZVC6jWkDzymlaUspbq/sF1WZ1/vfTtQbk6no61Ex+Wmzwnhw+73t3poK9+bEM7YKxFdFAMGsfoeQYTyppbipM8ZriVQA15KTLECA09D3byBmYZlXHsQCAPx1Oy8/PAf9kEbwskPYKNaVYp0DftyRrg+nndlHlwqW7sg+nZr+QERSwpgdbSZVoL9LPecYXvF3HA2xNEiDXWjA9UrCLAn+SxjZYSR0/4zT3tvZgNCvUa5WZEVpWyjXHeR6VQKeWDcvZPz7VeyI+LBIMYo8QfBmz1RIdA9ZaHC6iuT+R1lpuifhGsD+JwlzSTmO4qZFjVd48D/ggmqw2PnsLWA9Ttf7C6FXyGTCmOeHL0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
