travis:
  secure:
    BINSTAR_TOKEN: iNI9voP1u+JXb57KglKb+reOERRrI/C1neBF6tJhIDoXmJyAc3nRoscF2xEP/f6eIarh/T5kHT8D5mvueeKGZqG2LvCe6W5i2vqi+rGbayzssarzcNBgB6ZCIWZ/SQNfeBC/2qd05lrDtNdPFIS9USNLqhcd9L86or7PUKuXxBkl4pFO9GUA71GY+8hrYtsk6VeFnmM5jLf8WEwn7f0B8D7BgqxopeuK1AcATP750XsrJMl1WqbqZTNzKo0AMFOB+ZaZ7HEix9NBrImI5zyW+uVZxBoKLBPAGOifloZJuoLZtA45lYE3oa2eIoRPLeZvJQifb2XMqNH1URSKEoNf9ConzBJgl8qcAgOGEExbkYA0nfr2B7CMSvvryKKbr21A8QWbgcgqfduDmlqNJ2RkAWzquB6Ui+KywOPHj5hfRXazNjii+oKRWwY3Z7UKKWKENNVaTah7eJOxvMQGItlZbsq3Hw8/aKT1NUBlJcg14e9jJG00Ex6xBYp/iDrtrqBep+qmAwa8WQHejzT0UBj90aKLuUffd/z7DSkVIoeT8tfhRfdDZJIuSsNy4BDnB2MsYW8a9hudokVbSCilDyvI8eopdx8cVhGd/NUg0SZzgvT56elb/e2VR/0DW0ZVIaq4URd+VGbrhvepad4WxIOX+ZqTr3aN8n5zQMFVGUmjJJk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
