travis:
  secure:
    BINSTAR_TOKEN: a4CCmW/Gp5fR+YU24MvooIDsi+h7whBZp/eZJ0Zo2QKP9E+z1zwKCRLlSLpN3vfHVibmAGeKgttNIYPHAh/vZRXFjTsPkvWB3ZX2QP/Z1VW12b8P/71KGn8pCOP8N6J8C6Cz0TM69kKRBVLNO0mM0MzXMjTl0vYdgL70FzV/4JvfX9TIdexXnKuCzZb1LKPlyzuVMLDHjXKrTHzN0ztME8H2ZcwfCA9dgeKBFJdAGP0fm7H1r33WYpt95J8EHel+02Qz4Yck1QHcz2jVuqoHWhNMh9VddZlSmBBH/7mNRwdhDZfeEylBL160fcUWr+W20VXiqlsoGo7BDqrQbp+ScJsbZyqU+AxM4m/5UMniN13bID4Sl/n7wdyqRw0/0MdfkaI21ThqXi/L8wRYb/IKf46ojpKE5HbtbfaK2HU1TW5JXQftJYrBPH6VbTCefeEIFmjUFwca487rq8ioR+M7avR+LNJCTOQPc3EJcHfGkiJFZnpkWh3soQVSV3iZlCo9L9uIu5uEF0wDjSHTJEUMAuWiuMYMY/VVR/Fav5SXEsbKfQpaF9mtENzmrgI7Zkhmpt6NggGWAHR3IIZL5ACBcKImh/QYTboowq2UnuVTG0JUP7PhTSqhZ0ZP9OeSWnBR8zH6+zmbZAP1cKTDae0/l/rODBoiia3hqVbt8ygXEHY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
